#!/bin/sh

TOOLCHAINS_HOME=/opt/toolchains/uclibc-crosstools

export LIBS="-L."
export INCLUDES="-I${TOOLCHAINS_HOME}/include/c++/3.4.2 \
    -I${TOOLCHAINS_HOME}/mips-linux/sys-include \
    -I../../broadcom/cfm/inc"
export CFLAGS="${INCLUDES} ${LIBS}"
#export LDFLAGS="-static"
export CC="${TOOLCHAINS_HOME}/bin/mips-uclibc-gcc"
export LD="${TOOLCHAINS_HOME}/bin/mips-uclibc-ld"
export AR="${TOOLCHAINS_HOME}/bin/mips-uclibc-ar"
export RANLIB="${TOOLCHAINS_HOME}/bin/mips-uclibc-ranlib"
export STRIP="${TOOLCHAINS_HOME}/bin/mips-uclibc-strip"

export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${TOOLCHAINS_HOME}/lib
export PATH="${PATH}:${TOOLCHAINS_HOME}/bin"

#make -C libgpio_bcm963xx
make
