#!/bin/sh

TOOLCHAINS_HOME=/opt/toolchains/uclibc-crosstools
ROLEO_DIR=/opt/bcm963xx_router/userapps/roleo

export LIBS="-L${ROLEO_DIR}/ncurses-5.7/lib"
export LDFLGS="-lncurses"
export INCLUDES="-I${TOOLCHAINS_HOME}/include/c++/3.4.2 \
    -I${TOOLCHAINS_HOME}/mips-linux/sys-include \
    -I${ROLEO_DIR}/ncurses-5.7/include"
export CFLAGS="${INCLUDES} ${LIBS}"
export CXXFLAGS="${INCLUDES} ${LIBS}"
#export STUFF_CFLAGS="${INCLUDES} ${LIBS}"
#export LDFLAGS="-static"
export CC="${TOOLCHAINS_HOME}/bin/mips-uclibc-gcc"
export CXX="${TOOLCHAINS_HOME}/bin/mips-uclibc-g++"
export LD="${TOOLCHAINS_HOME}/bin/mips-uclibc-ld"
export AR="${TOOLCHAINS_HOME}/bin/mips-uclibc-ar"
export RANLIB="${TOOLCHAINS_HOME}/bin/mips-uclibc-ranlib"
export STRIP="${TOOLCHAINS_HOME}/bin/mips-uclibc-strip"

export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${TOOLCHAINS_HOME}/lib
export PATH="${PATH}:${TOOLCHAINS_HOME}/bin"

./configure --host=mips-linux --without-ncurses
