#!/bin/sh

TOOLCHAINS_HOME=/opt/toolchains/uclibc-crosstools

export LIBS="-L$TOOLCHAINS_HOME/mips-linux/lib"
export INCLUDES="-I${TOOLCHAINS_HOME}/include/c++/3.4.2 \
    -I${TOOLCHAINS_HOME}/mips-linux/sys-include"
export CFLAGS="-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 ${INCLUDES} ${LIBS}"
export CPPFLAGS="-D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64"
#export LDFLAGS="-static -ljpeg"
export CC="${TOOLCHAINS_HOME}/bin/mips-uclibc-gcc"
export LD="${TOOLCHAINS_HOME}/bin/mips-uclibc-ld"
export AR="${TOOLCHAINS_HOME}/bin/mips-uclibc-ar"
export RANLIB="${TOOLCHAINS_HOME}/bin/mips-uclibc-ranlib"
export STRIP="${TOOLCHAINS_HOME}/bin/mips-uclibc-strip"

export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${TOOLCHAINS_HOME}/lib
export PATH="${PATH}:${TOOLCHAINS_HOME}/bin"

./configure --host=mips-linux
