#!/bin/sh

TOOLCHAINS_HOME=/opt/toolchains/uclibc-crosstools
ROLEO_DIR=/opt/bcm963xx_router/userapps/roleo

export LIBS="-L$TOOLCHAINS_HOME/mips-linux/lib \
    -L${ROLEO_DIR}/jpeg-6b"
export INCLUDES="-I${TOOLCHAINS_HOME}/include/c++/3.4.2 \
    -I${TOOLCHAINS_HOME}/mips-linux/sys-include \
    -I${ROLEO_DIR}/jpeg-6b"
export CFLAGS="${INCLUDES} ${LIBS}"
#export LDFLAGS="-static -ljpeg"
export LDFLAGS="-ljpeg"
export CC="${TOOLCHAINS_HOME}/bin/mips-uclibc-gcc"
export LD="${TOOLCHAINS_HOME}/bin/mips-uclibc-ld"
export AR="${TOOLCHAINS_HOME}/bin/mips-uclibc-ar"
export RANLIB="${TOOLCHAINS_HOME}/bin/mips-uclibc-ranlib"
export STRIP="${TOOLCHAINS_HOME}/bin/mips-uclibc-strip"

export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${TOOLCHAINS_HOME}/lib
export PATH="${PATH}:${TOOLCHAINS_HOME}/bin"

./configure --host=mips-linux
